version: '3.8'

services:
  web:
    image: ghcr.io/codeyy/password-manager-pro:main # Use your GHCR image!
    ports:
      - "8000:8000"
    volumes:
      # Only map the database folder so your passwords don't disappear
      - ./database:/app/database 
    environment:
      - DATABASE_URL=sqlite:////app/database/passvault.db
    restart: always